#!/usr/bin/env python3
#this code can get divisors, proper_divisors or check if a number is perfect

#this gets the divisors of a number
def get_divisors(num):
    # all numbers that do not have a remainder are added to the list divisors
    divisors = [number for number in range(1, num + 1) if num % number == 0]
    return(divisors)

def get_proper_divisors(num):
    # all numbers that do not have a remainder and are not equal to themselves
    proper_divisors = [number for number in range(1, num) if num % number == 0 and number != num]
    return(proper_divisors)

def is_perfect(num):
    total = 0
    # calls proper_divisors
    proper_divisors = get_proper_divisors(num)
    # adds all numbers in proper_divisors together and then checks if the total of proper divisors is equal to the number inputed
    for numbers in proper_divisors:
        total = total + numbers
    
    if total == num:
        return(True) 

    else:
        return(False)
